Specify user and group in systemd unit file
YunoHost-Apps/jupyterlab_ynh pull request #90
Opened 2021-05-28 23:40 UTC by Jules-Bertholet

Fix CI warning

## Problem
- User and group were missing

## Solution
- Added them

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

2021-05-29 01:29 UTC, Jules-Bertholet commented
!testme

2021-05-29 09:18 UTC, ericgaspar requested changes
The CI still complains about `User:` not being set... Also I am not sure how systemd reacts to capitalization...

2021-05-29 09:18 UTC, ericgaspar commented on conf/systemd.service
> +GROUP=__APP__
```suggestion
User=__APP__
Group=__APP__
```

2021-05-29 14:19 UTC, ericgaspar commented
!testme

2021-05-29 22:54 UTC, Jules-Bertholet commented
CI passed, this is ready to merge

2021-05-30 06:45 UTC, ericgaspar commented
After installing amd login I get  `500 : Internal Server Error Error in Authenticator.pre_spawn_start: SubprocessError Exception occurred in preexec_fn.` error. I seems related to this issue: https://github.com/jupyterhub/jupyterhub/issues/1527

2021-05-30 21:04 UTC, Jules-Bertholet commented
!testme

2021-05-31 10:05 UTC, kay0u commented
Thank you for this very interesting PR!
I know it's very tempting to refactor scripts to avoid copying the same code everywhere, but we chose not to do that on the `example_ynh` template for some reason, and we want to keep the packages as close to that template as possible. Can you avoid doing this, please?

2021-05-31 18:27 UTC, Jules-Bertholet commented
> I know it's very tempting to refactor scripts to avoid copying the same code everywhere, but we chose not to do that on the `example_ynh` template for some reason, and we want to keep the packages as close to that template as possible. Can you avoid doing this, please?

It was so tempting that I proposed https://github.com/YunoHost/example_ynh/pull/164.

I've tested everything manually, this should be ready for review now

2021-06-07 20:14 UTC, ericgaspar requested changes
minor typos

2021-06-07 20:14 UTC, ericgaspar commented on scripts/install
> +ynh_script_progression --message="Building Jupyter lab for each user..." --weight=10
```suggestion
ynh_script_progression --message="Building JupyterLab for each user..." --weight=10
```

2021-06-07 20:14 UTC, ericgaspar commented on scripts/upgrade
> +ynh_script_progression --message="Building Jupyter lab for each user..." --weight=10
```suggestion
ynh_script_progression --message="Building JupyterLab for each user..." --weight=10
```

2021-06-07 20:36 UTC, ericgaspar approved these changes

2021-06-23 08:57 UTC, merged